//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostalWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_PEDIDO()
        {
            this.ORDEN_PEDIDO_PRODUCTO = new HashSet<ORDEN_PEDIDO_PRODUCTO>();
        }
    
        public int ID { get; set; }
        public string DETALLE { get; set; }
        public int PROVEEDOR_ID { get; set; }
        public int EMPLEADO_ID { get; set; }
        public string ESTADO { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_PEDIDO_PRODUCTO> ORDEN_PEDIDO_PRODUCTO { get; set; }
    }
}
